# learn tensors

`import libraries`

In [3]:
import torch
import numpy as np

`tensor initialization`

In [5]:
# directly from data
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
# from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [7]:
# from another tensor
x_ones = torch.ones_like(x_data)
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [9]:
# with random or constant values
shape = (2,3) # tuple of tensor dimensions

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.1479, 0.1182, 0.7567],
        [0.6268, 0.5236, 0.0535]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


`tensor attributes`

In [13]:
shape_for_tensor = (3,4)
tensor = torch.rand(shape_for_tensor)

tensor_shape = tensor.shape
print(tensor_shape)

tensor_datatype = tensor.dtype
print(tensor_datatype)

tensor_device = tensor.device
print(tensor_device)

torch.Size([3, 4])
torch.float32
cpu


`tensor operations`

In [19]:
# list of tensor operations can be obtained here - https://pytorch.org/docs/stable/torch.html

# indexing and slicing
tensor = torch.ones(4,4)
print(tensor)

tensor[:,1] = 0 # modifies the second column (index 1) of the tensor, setting all elements in that column to 0 
print(tensor)

tensor[:,1] = 1
print(tensor)

tensor[0,0] = 0 # specifically modifies the element of the first row, first column (index 0,0) of the tensor, setting it to 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [20]:
# joining tensors

t1 = torch.cat([tensor, tensor, tensor], dim=0) # concatenate along dimension 0 (rows) - stacks vertically
print(t1)

t2 = torch.cat([tensor, tensor, tensor], dim=1) # concatenate along dimension 1 (columns) - stacks horizontally
print(t2)

tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
