NUMPY - NUMERICAL PYTHON (RECAP)

In [1]:
import numpy as np



---

**1 - create numpy array**

In [3]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [4]:
# numpy array
np_arr = np.array([1,2,3,4,5])
print(np_arr)
type(np_arr)

[1 2 3 4 5]


numpy.ndarray

In [5]:
# create 1d array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
a.shape

(5,)

In [7]:
# create 2d array
b = np.array([(1,2,3,4),(4,3,2,1)])
print(b)

[[1 2 3 4]
 [4 3 2 1]]


In [9]:
b.shape

(2, 4)

In [10]:
# changing the data type of numpy array
c = np.array([(1,2,3,4),(4,3,2,1)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [4. 3. 2. 1.]]




---

**2 - initial placeholders in numpy array**

In [11]:
# create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
# create a numpy array of zeros
y = np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# create a numpy array of a specific value
z = np.full((3,3),5)
print(z)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [14]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
# create numpy array with random values (between 0 and 1)
b = np.random.random((3,4))
print(b)

[[0.95084586 0.06903806 0.02994203 0.29917479]
 [0.35482706 0.40019513 0.52197332 0.29468067]
 [0.44271477 0.32243022 0.1921696  0.38421954]]


In [16]:
# create numpy array with random values (integer values)
c = np.random.randint(10,100,(3,6))
print(c)

[[61 43 75 99 25 60]
 [42 55 85 99 57 89]
 [30 33 22 87 61 47]]


In [17]:
# create numpy array with evenly spaced values (specifying the number of values needed)
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [19]:
# create numpy array with evenly spaced values (specifying the step)
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [20]:
# convert list into a numpy array
list2 = [1,2,3,4,5]

np_arr = np.asarray(list2)
print(np_arr)

[1 2 3 4 5]




---

**3 - analyzing numpy arrays**

In [21]:
c = np.random.randint(10,90,(5,5))
print(c)

[[14 36 37 47 68]
 [26 30 56 56 47]
 [83 27 26 88 24]
 [52 68 45 15 14]
 [88 68 43 12 48]]


In [22]:
# array dimension?
print(c.shape)

(5, 5)


In [23]:
# number of dimensions?
print(c.ndim)

2


In [24]:
# number of elements in array?
print(c.size)

25


In [25]:
# data type of values in array?
print(c.dtype)

int64




---

**4 - mathematical operations on numpy arrays**

In [26]:
# method 1 - add, subtract, multiply and divide
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

[[6 3 4]
 [1 8 2]
 [4 6 4]]
[[11 12 17]
 [16 12 15]
 [15 11 10]]


In [27]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[17 15 21]
 [17 20 17]
 [19 17 14]]
[[ -5  -9 -13]
 [-15  -4 -13]
 [-11  -5  -6]]
[[66 36 68]
 [16 96 30]
 [60 66 40]]
[[0.54545455 0.25       0.23529412]
 [0.0625     0.66666667 0.13333333]
 [0.26666667 0.54545455 0.4       ]]


In [28]:
# method 1 - add, subtract, multiply and divide
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

[[7 5 8]
 [0 3 9]
 [7 6 5]]
[[14 11 10]
 [15 17 15]
 [14 15 14]]


In [29]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[21 16 18]
 [15 20 24]
 [21 21 19]]
[[ -7  -6  -2]
 [-15 -14  -6]
 [ -7  -9  -9]]
[[ 98  55  80]
 [  0  51 135]
 [ 98  90  70]]
[[0.5        0.45454545 0.8       ]
 [0.         0.17647059 0.6       ]
 [0.5        0.4        0.35714286]]




---

**5 - array manipulation**

In [31]:
# method 1 - transpose
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 6 9]
 [2 4 3]]
(2, 3)


In [32]:
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 2]
 [6 4]
 [9 3]]
(3, 2)


In [33]:
# method 2 - transpose
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 7 5]
 [1 6 8]]
(2, 3)


In [34]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[1 1]
 [7 6]
 [5 8]]
(3, 2)


In [35]:
# reshape a numpy array
a = np.random.randint(0,18,(2,3))
print(a)
print(a.shape)

[[13 11 13]
 [13 16 15]]
(2, 3)


In [36]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[13 11]
 [13 13]
 [16 15]]
(3, 2)
